obj-$(CONFIG_USE_DIRECT_IS_CONTROL) += fimc-is-device-module-base.o

obj-$(CONFIG_CAMERA_CIS_6B2_OBJ) += fimc-is-device-module-6b2.o
obj-$(CONFIG_CAMERA_CIS_5E2_OBJ) += fimc-is-device-module-5e2.o
obj-$(CONFIG_CAMERA_CIS_5E3_OBJ) += fimc-is-device-module-5e3.o
obj-$(CONFIG_CAMERA_CIS_5E6_OBJ) += fimc-is-device-module-5e6.o
obj-$(CONFIG_CAMERA_CIS_5F1_OBJ) += fimc-is-device-module-5f1.o
obj-$(CONFIG_CAMERA_CIS_4H5YC_OBJ) += fimc-is-device-module-4h5yc.o
obj-$(CONFIG_CAMERA_CIS_4H5_OBJ) += fimc-is-device-module-4h5.o
obj-$(CONFIG_CAMERA_CIS_2P2_OBJ) += fimc-is-device-module-2p2.o
obj-$(CONFIG_CAMERA_CIS_2P6_OBJ) += fimc-is-device-module-2p6.o
obj-$(CONFIG_CAMERA_CIS_2P8_OBJ) += fimc-is-device-module-2p8.o
obj-$(CONFIG_CAMERA_CIS_3P3_OBJ) += fimc-is-device-module-3p3.o
obj-$(CONFIG_CAMERA_CIS_3P8_OBJ) += fimc-is-device-module-3p8.o
obj-$(CONFIG_CAMERA_CIS_3L2_OBJ) += fimc-is-device-module-3l2.o
obj-$(CONFIG_CAMERA_CIS_3L6_OBJ) += fimc-is-device-module-3l6.o
obj-$(CONFIG_CAMERA_CIS_3M3_OBJ) += fimc-is-device-module-3m3.o
obj-$(CONFIG_CAMERA_CIS_SR544_OBJ) += fimc-is-device-module-sr544.o
obj-$(CONFIG_CAMERA_CIS_SR259_OBJ) += fimc-is-device-module-sr259.o
obj-$(CONFIG_CAMERA_CIS_IMX258_OBJ) += fimc-is-device-module-imx258.o
obj-$(CONFIG_CAMERA_CIS_IMX219_OBJ) += fimc-is-device-module-imx219.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/sensor/module_framework
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/sensor
