#
# Makefile for the drivers of Marvell devices.
#

#obj-$(CONFIG_MRVL_WL_SD8887) += sd8887/
#obj-$(CONFIG_MRVL_WL_SD8777) += sd8777/
#obj-$(CONFIG_MRVL_WL_SD8787) += sd8787/
#obj-$(CONFIG_MRVL_WL_SD8897) += sd8897/
obj-$(CONFIG_MRVL_WL_SD8977) += sd8977/
#obj-$(CONFIG_MRVL_WL_SD8XXX) += sd8777/ sd8787/ sd8887/ sd8897/ sd8977/
obj-$(CONFIG_MRVL_WL_SD8XXX) += sd8977/

