#
# Makefile for Bosch sensor driver.
#
obj-$(CONFIG_SENSORS_BHI)    += bstclass.o
obj-$(CONFIG_SENSORS_BHI)    += bhy_core.o
obj-$(CONFIG_SENSORS_BHI)    += bhy_i2c.o
obj-$(CONFIG_SENSORS_BHI_BMP280) += pressure_bmp280.o