#
# Makefile for MELFAS MIP4 Touchkey driver
#

obj-$(CONFIG_KEYBOARD_MELFAS_MHS204) += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mhs204.o mip4_sec.o
obj-$(CONFIG_KEYBOARD_MELFAS_MHS204G) += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mhs204.o mip4_sec.o
obj-$(CONFIG_KEYBOARD_MELFAS_MHS2041) += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mhs2041.o mip4_sec.o
obj-$(CONFIG_KEYBOARD_MELFAS_MHS2041B) += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mhs2041.o mip4_sec.o

